# Generated by Django 4.1.2 on 2022-12-14 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_course_facults'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='teacher_profile_img',
            new_name='student_profile_img',
        ),
    ]
