# Generated by Django 4.1.2 on 2022-12-14 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_rename_teacher_profile_img_student_student_profile_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='mobile_number',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='mobile_number',
        ),
    ]
