# Generated by Django 4.1.2 on 2022-12-14 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_remove_student_mobile_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='facult',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='studylevel',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='necessary_categories',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
